/**
 * Curated M&A glossary — 55 bilingual entries.
 *
 * Kept in a single file to stay under AGENTS.md's ≤10 directory children
 * rule and so the data reads as a single reviewable change. Scale to the
 * ROADMAP § 1.4 target of 300+ terms across follow-up passes.
 */

import type { GlossaryEntry } from './types';

export const GLOSSARY_ENTRIES: readonly GlossaryEntry[] = [
  {
    id: 'nda',
    termFr: "Accord de confidentialité (NDA)",
    termEn: 'Non-disclosure agreement',
    definitionFr: "Contrat par lequel les parties s'engagent à ne pas divulguer les informations échangées dans le cadre de l'analyse d'une opération.",
    definitionEn: 'Contract binding parties to confidentiality over information exchanged while assessing a transaction.',
    category: 'documents',
  },
  {
    id: 'teaser',
    termFr: 'Teaser',
    termEn: 'Teaser',
    definitionFr: "Document court (1 à 3 pages) présentant anonymement la cible et sollicitant l'intérêt d'acquéreurs potentiels.",
    definitionEn: 'Short blind profile (1–3 pages) pitching the target to prospective buyers without revealing its identity.',
    category: 'documents',
    relatedIds: ['im', 'nda'],
  },
  {
    id: 'im',
    termFr: "Mémorandum d'information (IM)",
    termEn: 'Information memorandum',
    definitionFr: "Dossier complet (40 à 80 pages) remis aux acquéreurs sous NDA, décrivant l'entreprise, son marché, ses finances et les modalités envisagées.",
    definitionEn: 'Comprehensive document (40–80 pages) delivered under NDA covering the target, its market, financials and proposed transaction terms.',
    category: 'documents',
    relatedIds: ['teaser', 'nda'],
  },
  {
    id: 'loi',
    termFr: "Lettre d'intention (LOI)",
    termEn: 'Letter of intent',
    definitionFr: "Document non-liant (sauf clauses d'exclusivité et de confidentialité) formalisant l'intérêt d'un acquéreur et les grandes lignes d'une offre.",
    definitionEn: 'Mostly non-binding instrument (save for exclusivity and confidentiality clauses) outlining a prospective acquirer’s interest and the main offer terms.',
    category: 'documents',
    relatedIds: ['spa'],
  },
  {
    id: 'spa',
    termFr: "Contrat de cession (SPA)",
    termEn: 'Share purchase agreement',
    definitionFr: "Contrat de cession d'actions ou de parts sociales, pièce maîtresse d'un closing.",
    definitionEn: 'Share or equity purchase agreement, the principal contract signed at closing.',
    category: 'deal_structure',
    relatedIds: ['closing', 'loi'],
  },
  {
    id: 'apa',
    termFr: "Contrat de cession d'actifs (APA)",
    termEn: 'Asset purchase agreement',
    definitionFr: "Contrat de cession portant sur un actif ou un fonds de commerce plutôt que sur les titres de la société.",
    definitionEn: 'Transaction where specific assets (or a business) are acquired rather than the shares of the owning entity.',
    category: 'deal_structure',
  },
  {
    id: 'mandat_cession',
    termFr: 'Mandat de cession',
    termEn: 'Sell-side mandate',
    definitionFr: "Contrat engageant un conseil M&A à rechercher un acquéreur pour le compte du cédant.",
    definitionEn: 'Engagement letter under which an M&A advisor is tasked with finding a buyer on behalf of a seller.',
    category: 'process',
  },
  {
    id: 'mandat_achat',
    termFr: "Mandat d'achat",
    termEn: 'Buy-side mandate',
    definitionFr: "Contrat engageant un conseil M&A à identifier des cibles pour le compte d'un acquéreur.",
    definitionEn: 'Engagement where an M&A advisor sources acquisition targets for a buyer.',
    category: 'process',
  },
  {
    id: 'due_diligence',
    termFr: 'Due diligence',
    termEn: 'Due diligence',
    definitionFr: "Phase d'investigation approfondie (financière, juridique, fiscale, sociale, IT, environnementale) menée par l'acquéreur après la LOI.",
    definitionEn: 'Buyer-led deep dive (financial, legal, tax, HR, IT, environmental) typically performed after the LOI.',
    category: 'due_diligence',
  },
  {
    id: 'vdr',
    termFr: 'Data room',
    termEn: 'Virtual data room',
    definitionFr: "Espace numérique sécurisé regroupant les documents mis à disposition des acquéreurs pendant la due diligence.",
    definitionEn: 'Secure digital workspace holding the documents shared with prospective buyers during due diligence.',
    category: 'due_diligence',
  },
  {
    id: 'closing',
    termFr: 'Closing',
    termEn: 'Closing',
    definitionFr: "Date à laquelle la cession est formellement réalisée (signature du SPA, paiement du prix, transfert de propriété).",
    definitionEn: 'Date on which the transaction is completed — SPA executed, purchase price paid and ownership transferred.',
    category: 'process',
    relatedIds: ['spa'],
  },
  {
    id: 'signing',
    termFr: 'Signing',
    termEn: 'Signing',
    definitionFr: "Signature des contrats définitifs, précédant souvent le closing de quelques semaines (conditions suspensives).",
    definitionEn: 'Execution of the definitive documents, often preceding closing by a few weeks while conditions precedent are cleared.',
    category: 'process',
    relatedIds: ['closing'],
  },
  {
    id: 'conditions_suspensives',
    termFr: 'Conditions suspensives',
    termEn: 'Conditions precedent',
    definitionFr: "Conditions dont la réalisation est nécessaire avant le closing (autorisations réglementaires, accord des tiers, levées de sûretés).",
    definitionEn: 'Obligations that must be satisfied between signing and closing, such as regulatory clearance, third-party consents, or release of liens.',
    category: 'legal',
  },
  {
    id: 'earn_out',
    termFr: 'Earn-out',
    termEn: 'Earn-out',
    definitionFr: "Complément de prix conditionné à la performance future de la société (CA, EBE, indicateurs spécifiques).",
    definitionEn: 'Deferred portion of the purchase price contingent on future performance metrics (revenue, EBITDA, or custom KPIs).',
    category: 'deal_structure',
  },
  {
    id: 'vendor_loan',
    termFr: 'Crédit vendeur',
    termEn: 'Vendor loan',
    definitionFr: "Part du prix de cession consentie par le vendeur sous forme de prêt remboursable par l'acquéreur.",
    definitionEn: 'Portion of the purchase price extended by the seller as a loan repayable by the buyer.',
    category: 'deal_structure',
  },
  {
    id: 'escrow',
    termFr: 'Séquestre',
    termEn: 'Escrow',
    definitionFr: "Fraction du prix conservée par un tiers pendant une durée convenue pour garantir les déclarations du vendeur.",
    definitionEn: 'Portion of the purchase price held by a third party for an agreed period to back up the seller’s warranties.',
    category: 'deal_structure',
  },
  {
    id: 'garantie_passif',
    termFr: "Garantie d'actif et de passif (GAP)",
    termEn: 'Representations and warranties',
    definitionFr: "Clause du SPA par laquelle le vendeur garantit l'exactitude des comptes et l'absence de passifs non révélés.",
    definitionEn: 'SPA clause where the seller guarantees the accuracy of the accounts and the absence of undisclosed liabilities.',
    category: 'legal',
    relatedIds: ['spa'],
  },
  {
    id: 'rolling_over',
    termFr: 'Rolling over',
    termEn: 'Rolling over',
    definitionFr: "Réinvestissement d'une partie du produit de cession par le vendeur dans la structure d'acquisition.",
    definitionEn: 'Reinvestment by the seller of part of the sale proceeds into the acquisition vehicle.',
    category: 'deal_structure',
  },
  {
    id: 'management_package',
    termFr: 'Management package',
    termEn: 'Management package',
    definitionFr: "Dispositif d'intéressement proposé aux dirigeants (BSPCE, BSA, actions de préférence) lors d'une opération de LBO.",
    definitionEn: 'Equity incentive scheme (warrants, preference shares, sweet equity) granted to managers in an LBO.',
    category: 'governance',
  },
  {
    id: 'lbo',
    termFr: 'LBO (Leveraged Buyout)',
    termEn: 'Leveraged buyout',
    definitionFr: "Acquisition financée majoritairement par dette, remboursée par les cash-flows de la société cible.",
    definitionEn: 'Acquisition primarily funded by debt, serviced from the target’s future cash flows.',
    category: 'deal_structure',
  },
  {
    id: 'mbo',
    termFr: 'MBO (Management Buyout)',
    termEn: 'Management buyout',
    definitionFr: "Reprise de l'entreprise par son équipe dirigeante, souvent avec le concours d'un fonds.",
    definitionEn: 'Acquisition of a company by its existing management team, frequently with private equity backing.',
    category: 'deal_structure',
  },
  {
    id: 'obo',
    termFr: 'OBO (Owner Buyout)',
    termEn: 'Owner buyout',
    definitionFr: "Opération permettant au dirigeant-actionnaire de réaliser une partie de son capital tout en restant aux commandes.",
    definitionEn: 'Transaction enabling an owner-manager to monetise part of their stake while remaining in control.',
    category: 'deal_structure',
  },
  {
    id: 'ebitda',
    termFr: "Excédent brut d'exploitation (EBE/EBITDA)",
    termEn: 'EBITDA',
    definitionFr: "Résultat opérationnel avant amortissements et provisions, proxy de la capacité bénéficiaire récurrente.",
    definitionEn: 'Earnings before interest, taxes, depreciation and amortisation — a proxy for recurring operating profitability.',
    category: 'finance',
    relatedIds: ['multiples'],
  },
  {
    id: 'ev',
    termFr: "Valeur d'entreprise",
    termEn: 'Enterprise value',
    definitionFr: "Valeur de l'actif économique, indépendante de la structure financière (capitalisation + dette nette).",
    definitionEn: 'Value of the operating business independent of its financing mix (equity value + net debt).',
    category: 'valuation',
  },
  {
    id: 'equity_value',
    termFr: 'Valeur des capitaux propres',
    termEn: 'Equity value',
    definitionFr: "Valeur des fonds propres revenant aux actionnaires, calculée en soustrayant la dette nette de la valeur d'entreprise.",
    definitionEn: 'Value attributable to shareholders, obtained by subtracting net debt from enterprise value.',
    category: 'valuation',
  },
  {
    id: 'multiples',
    termFr: 'Multiples de comparables',
    termEn: 'Trading multiples',
    definitionFr: "Méthode consistant à appliquer des multiples observés chez des pairs cotés (EV/EBE, EV/CA, P/E) aux agrégats de la cible.",
    definitionEn: 'Valuation approach applying trading multiples (EV/EBITDA, EV/Revenue, P/E) observed on listed peers to the target’s aggregates.',
    category: 'valuation',
  },
  {
    id: 'dcf',
    termFr: 'DCF — Flux de trésorerie actualisés',
    termEn: 'Discounted cash flow',
    definitionFr: "Méthode de valorisation fondée sur l'actualisation des flux de trésorerie futurs au coût du capital (WACC).",
    definitionEn: 'Valuation method that discounts projected free cash flows to present value using the weighted average cost of capital.',
    category: 'valuation',
  },
  {
    id: 'wacc',
    termFr: 'Coût moyen pondéré du capital (WACC)',
    termEn: 'Weighted average cost of capital',
    definitionFr: "Moyenne pondérée du coût des fonds propres et du coût de la dette, utilisée comme taux d'actualisation du DCF.",
    definitionEn: 'Weighted average of the cost of equity and the after-tax cost of debt used as the discount rate in a DCF.',
    category: 'finance',
  },
  {
    id: 'anr',
    termFr: 'Actif net réévalué (ANR)',
    termEn: 'Adjusted net assets',
    definitionFr: "Méthode patrimoniale évaluant la société à partir de ses actifs et passifs réévalués à leur juste valeur.",
    definitionEn: 'Asset-based method valuing a company through its assets and liabilities restated to fair value.',
    category: 'valuation',
  },
  {
    id: 'regle_pouce',
    termFr: 'Règle du pouce',
    termEn: 'Rule of thumb',
    definitionFr: "Multiplicateur empirique propre à un secteur (par exemple × CA pour une pharmacie).",
    definitionEn: 'Sector-specific empirical multiplier (e.g. × revenue for a pharmacy).',
    category: 'valuation',
  },
  {
    id: 'bfr',
    termFr: 'Besoin en fonds de roulement (BFR)',
    termEn: 'Working capital',
    definitionFr: "Écart entre actif et passif d'exploitation, à surveiller dans les ajustements de prix au closing.",
    definitionEn: 'Gap between operating assets and operating liabilities, monitored closely during closing price adjustments.',
    category: 'finance',
  },
  {
    id: 'capex',
    termFr: "Dépenses d'investissement (CAPEX)",
    termEn: 'Capital expenditure',
    definitionFr: "Investissements capitalisés en immobilisations, constitutifs du plan d'affaires.",
    definitionEn: 'Investment spending capitalised as fixed assets, a cornerstone of the business plan.',
    category: 'finance',
  },
  {
    id: 'net_debt',
    termFr: 'Dette nette',
    termEn: 'Net debt',
    definitionFr: "Dette financière brute diminuée de la trésorerie disponible, soustraite de la valeur d'entreprise.",
    definitionEn: 'Gross financial debt minus available cash, deducted from enterprise value.',
    category: 'finance',
    relatedIds: ['ev', 'equity_value'],
  },
  {
    id: 'exclusivity',
    termFr: "Clause d'exclusivité",
    termEn: 'Exclusivity clause',
    definitionFr: "Engagement du vendeur à ne pas négocier avec d'autres acquéreurs pendant une durée définie.",
    definitionEn: 'Seller’s commitment not to negotiate with other buyers for a defined period.',
    category: 'legal',
    relatedIds: ['loi'],
  },
  {
    id: 'standstill',
    termFr: 'Clause de standstill',
    termEn: 'Standstill clause',
    definitionFr: "Engagement de ne pas acquérir de titres supplémentaires ni lancer d'offre non sollicitée pendant une durée donnée.",
    definitionEn: 'Undertaking not to acquire additional shares or launch an unsolicited offer for a defined period.',
    category: 'legal',
  },
  {
    id: 'mac',
    termFr: 'MAC — Changement défavorable significatif',
    termEn: 'Material adverse change',
    definitionFr: "Clause autorisant l'acquéreur à se retirer en cas d'événement matériellement défavorable avant closing.",
    definitionEn: 'Clause entitling the buyer to walk away when a materially adverse event occurs before closing.',
    category: 'legal',
  },
  {
    id: 'spa_indemnification',
    termFr: "Clause d'indemnisation",
    termEn: 'Indemnification clause',
    definitionFr: "Mécanisme par lequel le vendeur indemnise l'acquéreur pour les pertes liées à un manquement à une déclaration de garantie.",
    definitionEn: 'Mechanism under which the seller indemnifies the buyer for losses stemming from a breach of a representation or warranty.',
    category: 'legal',
    relatedIds: ['garantie_passif'],
  },
  {
    id: 'locked_box',
    termFr: 'Locked box',
    termEn: 'Locked box',
    definitionFr: "Mécanisme de prix fixe calculé à partir d'un bilan de référence antérieur au signing, sans ajustement au closing.",
    definitionEn: 'Pricing mechanism using a reference balance sheet struck before signing, without closing adjustments.',
    category: 'deal_structure',
  },
  {
    id: 'completion_accounts',
    termFr: 'Completion accounts',
    termEn: 'Completion accounts',
    definitionFr: "Mécanisme de prix ajusté au closing sur la base d'un bilan arrêté à cette date.",
    definitionEn: 'Pricing mechanism adjusted at closing against a balance sheet drawn up at that date.',
    category: 'deal_structure',
  },
  {
    id: 'sha',
    termFr: "Pacte d'actionnaires (SHA)",
    termEn: 'Shareholders’ agreement',
    definitionFr: "Convention organisant les relations entre actionnaires post-closing (gouvernance, sorties, préemption).",
    definitionEn: 'Post-closing contract governing the relationships between shareholders (governance, exit, pre-emption).',
    category: 'governance',
  },
  {
    id: 'drag_along',
    termFr: 'Clause de sortie forcée (drag-along)',
    termEn: 'Drag-along right',
    definitionFr: "Droit permettant à un actionnaire majoritaire d'obliger les minoritaires à céder leurs titres aux mêmes conditions.",
    definitionEn: 'Right enabling a majority shareholder to force minorities to sell on the same terms.',
    category: 'governance',
  },
  {
    id: 'tag_along',
    termFr: 'Clause de sortie conjointe (tag-along)',
    termEn: 'Tag-along right',
    definitionFr: "Droit permettant aux minoritaires de céder leurs titres aux conditions obtenues par le majoritaire.",
    definitionEn: 'Right allowing minority shareholders to sell on the same terms as the majority shareholder.',
    category: 'governance',
  },
  {
    id: 'preemption',
    termFr: 'Droit de préemption',
    termEn: 'Pre-emption right',
    definitionFr: "Droit prioritaire d'achat en cas de cession de titres par un autre actionnaire.",
    definitionEn: 'Priority right to purchase shares being transferred by another shareholder.',
    category: 'governance',
  },
  {
    id: 'bsa',
    termFr: "Bons de souscription d'actions (BSA)",
    termEn: 'Share warrants',
    definitionFr: "Titres donnant le droit de souscrire à des actions à un prix et dans des délais convenus.",
    definitionEn: 'Securities granting the right to subscribe to shares at an agreed price and within an agreed period.',
    category: 'finance',
  },
  {
    id: 'bspce',
    termFr: "BSPCE",
    termEn: 'Founder / employee warrants (BSPCE)',
    definitionFr: "Bons réservés aux dirigeants et salariés de PME innovantes, permettant l'acquisition d'actions à un prix fixe.",
    definitionEn: 'Warrants reserved for founders and employees of qualifying French startups, allowing share purchases at a fixed strike.',
    category: 'finance',
  },
  {
    id: 'forme_juridique',
    termFr: 'Forme juridique',
    termEn: 'Legal form',
    definitionFr: "Structure juridique de la société (SAS, SARL, SA, SCI, EURL, etc.) qui détermine gouvernance et fiscalité.",
    definitionEn: 'Legal structure of the company (SAS, SARL, SA, SCI, EURL, etc.) driving governance and tax treatment.',
    category: 'legal',
  },
  {
    id: 'kbis',
    termFr: 'Kbis',
    termEn: 'Kbis extract',
    definitionFr: "Extrait officiel d'immatriculation au Registre du Commerce et des Sociétés, attestant l'existence légale d'une société.",
    definitionEn: 'Official extract from the Trade and Companies Register evidencing a company’s legal existence.',
    category: 'legal',
  },
  {
    id: 'beneficial_owner',
    termFr: 'Bénéficiaire effectif',
    termEn: 'Beneficial owner',
    definitionFr: "Personne physique qui, in fine, contrôle une société via une chaîne de participation (au-delà de 25%).",
    definitionEn: 'Natural person who ultimately owns or controls a company through a chain of ownership exceeding 25%.',
    category: 'governance',
  },
  {
    id: 'procedure_collective',
    termFr: 'Procédure collective',
    termEn: 'Collective insolvency proceeding',
    definitionFr: "Procédure judiciaire (sauvegarde, redressement, liquidation) visant une société en difficulté.",
    definitionEn: 'Judicial proceeding (safeguard, reorganisation, liquidation) opened against a distressed company.',
    category: 'legal',
  },
  {
    id: 'pai',
    termFr: "Processus d'appels d'offres (process)",
    termEn: 'Sale process',
    definitionFr: "Processus structuré de cession, enchaînant teaser, IM, offres indicatives, offres fermes et DD.",
    definitionEn: 'Structured sale process running teaser → IM → non-binding offers → binding offers → due diligence.',
    category: 'process',
    relatedIds: ['teaser', 'im'],
  },
  {
    id: 'term_sheet',
    termFr: 'Term sheet',
    termEn: 'Term sheet',
    definitionFr: "Résumé des principales conditions d'une transaction, intermédiaire entre discussion et LOI formelle.",
    definitionEn: 'Summary of a transaction’s main conditions, bridging early discussions and a formal LOI.',
    category: 'documents',
  },
  {
    id: 'kyc',
    termFr: 'KYC',
    termEn: 'KYC',
    definitionFr: "Procédures d'identification des parties (Know Your Customer), requises pour lutter contre le blanchiment.",
    definitionEn: 'Counterparty-identification procedures required by anti-money-laundering regulations.',
    category: 'due_diligence',
  },
  {
    id: 'aml',
    termFr: 'LCB-FT',
    termEn: 'AML/CFT',
    definitionFr: "Lutte contre le blanchiment de capitaux et le financement du terrorisme — obligations réglementaires des conseils.",
    definitionEn: 'Anti-money-laundering and counter-terrorist-financing regime imposing obligations on advisors.',
    category: 'due_diligence',
  },
  {
    id: 'competition_clearance',
    termFr: "Autorisation de l'Autorité de la concurrence",
    termEn: 'Competition authority clearance',
    definitionFr: "Notification obligatoire au-delà de seuils de chiffre d'affaires — condition suspensive fréquente.",
    definitionEn: 'Mandatory merger notification above revenue thresholds, a frequent condition precedent.',
    category: 'legal',
  },
  {
    id: 'synergies',
    termFr: 'Synergies',
    termEn: 'Synergies',
    definitionFr: "Gains (coûts ou revenus) attendus du rapprochement, justifiant tout ou partie d'une prime d'acquisition.",
    definitionEn: 'Revenue or cost savings expected from the combination, justifying part of the acquisition premium.',
    category: 'finance',
  },
];
