/**
 * @license
 * Copyright 2025 AionUi (aionui.com)
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * LOI Template Renderer
 *
 * Produces a structured Letter of Intent markdown document from template
 * variables. Deterministic, local renderer — no Flowise call required.
 */

import type { RendererFn } from './types';

/**
 * Render an LOI document in markdown.
 *
 * Required variables: `dealId`, `buyerName`, `targetName`
 * Optional variables: `indicativePrice`, `exclusivityPeriod`
 */
export const renderLoi: RendererFn = (variables) => {
  const buyerName = String(variables.buyerName ?? 'Buyer');
  const targetName = String(variables.targetName ?? 'Target Company');
  const indicativePrice = variables.indicativePrice ? String(variables.indicativePrice) : null;
  const exclusivityPeriod = variables.exclusivityPeriod ? String(variables.exclusivityPeriod) : '60';

  const lines: string[] = [
    `# Letter of Intent`,
    '',
    `**From:** ${buyerName} ("Buyer")`,
    `**To:** ${targetName} ("Target")`,
    '',
    '---',
    '',
    '## 1. Introduction',
    '',
    `This Letter of Intent ("LOI") sets forth the principal terms of the proposed transaction (the "Transaction") between ${buyerName} and ${targetName}. This LOI is intended to serve as a basis for further negotiations and, except as otherwise provided herein, is non-binding.`,
    '',
    '## 2. Proposed Transaction',
    '',
    `The Buyer proposes to acquire a controlling interest in the Target, subject to satisfactory completion of due diligence, negotiation of definitive agreements, and other customary conditions.`,
    '',
    '## 3. Indicative Price',
    '',
    indicativePrice
      ? `Based on preliminary information, the Buyer proposes an indicative enterprise value of **${indicativePrice}**. The final purchase price will be determined based on the results of due diligence and is subject to adjustment.`
      : 'The purchase price will be determined based on the results of due diligence and will be negotiated in good faith by the parties.',
    '',
    '## 4. Exclusivity',
    '',
    `The Target agrees to negotiate exclusively with the Buyer for a period of **${exclusivityPeriod} days** from the date of execution of this LOI. During this period, the Target shall not solicit, initiate, or entertain discussions with any third party regarding a potential acquisition or similar transaction.`,
    '',
    '## 5. Due Diligence',
    '',
    'The Transaction is subject to the Buyer completing a satisfactory due diligence review of the Target. The Target shall provide the Buyer and its advisors with reasonable access to books, records, facilities, and management personnel.',
    '',
    '## 6. Confidentiality',
    '',
    'The existence and terms of this LOI, and all information exchanged between the parties in connection with the proposed Transaction, shall be treated as confidential and subject to the terms of any existing Non-Disclosure Agreement between the parties.',
    '',
    '## 7. Binding Provisions',
    '',
    'Notwithstanding the non-binding nature of this LOI, the following provisions shall be binding upon execution:',
    '',
    '- **Confidentiality** (Section 6)',
    '- **Exclusivity** (Section 4)',
    '- **Expenses** — Each party shall bear its own expenses related to the proposed Transaction.',
    '',
    '## 8. Next Steps',
    '',
    'Upon mutual agreement on the terms outlined herein, the parties will proceed to negotiate and execute definitive agreements as soon as practicable.',
    '',
    '---',
    '',
    `**Buyer:** ${buyerName}`,
    `**Target:** ${targetName}`,
    '',
    `*This document was generated by Largo M&A Assistant. Review by qualified legal counsel is recommended before execution.*`,
  ];

  return lines.join('\n');
};
