/**
 * @license
 * Copyright 2025 AionUi (aionui.com)
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * NDA Template Renderer
 *
 * Produces a structured Non-Disclosure Agreement markdown document from
 * template variables. This is a deterministic, local renderer that does
 * not require a Flowise call.
 */

import type { RendererFn } from './types';

/**
 * Render an NDA document in markdown.
 *
 * Required variables: `dealId`, `disclosingParty`, `receivingParty`
 * Optional variables: `jurisdiction`, `durationMonths`
 */
export const renderNda: RendererFn = (variables) => {
  const disclosingParty = String(variables.disclosingParty ?? 'Disclosing Party');
  const receivingParty = String(variables.receivingParty ?? 'Receiving Party');
  const jurisdiction = variables.jurisdiction ? String(variables.jurisdiction) : 'Applicable Jurisdiction';
  const durationMonths = variables.durationMonths ? String(variables.durationMonths) : '24';

  const lines: string[] = [
    `# Non-Disclosure Agreement`,
    '',
    `**Between**`,
    '',
    `**${disclosingParty}** ("Disclosing Party")`,
    `**${receivingParty}** ("Receiving Party")`,
    '',
    '---',
    '',
    '## 1. Purpose',
    '',
    'The Disclosing Party intends to disclose certain confidential information to the Receiving Party for the purpose of evaluating a potential business transaction or collaboration (the "Purpose").',
    '',
    '## 2. Definition of Confidential Information',
    '',
    '"Confidential Information" means all information disclosed by the Disclosing Party to the Receiving Party, whether orally, in writing, or by any other means, that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure.',
    '',
    '## 3. Obligations of the Receiving Party',
    '',
    'The Receiving Party shall:',
    '',
    '- Hold and maintain the Confidential Information in strict confidence;',
    '- Not disclose any Confidential Information to third parties without prior written consent;',
    '- Use the Confidential Information solely for the Purpose;',
    '- Protect the Confidential Information using the same degree of care it uses to protect its own confidential information, but in no event less than reasonable care.',
    '',
    '## 4. Exclusions',
    '',
    'Confidential Information does not include information that:',
    '',
    '- Is or becomes publicly available through no fault of the Receiving Party;',
    "- Was already in the Receiving Party's possession before disclosure;",
    '- Is independently developed by the Receiving Party without use of the Confidential Information;',
    '- Is rightfully obtained from a third party without restriction on disclosure.',
    '',
    '## 5. Term',
    '',
    `This Agreement shall remain in effect for a period of **${durationMonths} months** from the date of execution.`,
    '',
    '## 6. Governing Law',
    '',
    `This Agreement shall be governed by and construed in accordance with the laws of **${jurisdiction}**.`,
    '',
    '## 7. Remedies',
    '',
    'The Disclosing Party shall be entitled to seek injunctive relief for any breach or threatened breach of this Agreement, in addition to any other remedies available at law or in equity.',
    '',
    '## 8. Return of Information',
    '',
    'Upon written request by the Disclosing Party, or upon termination of discussions, the Receiving Party shall promptly return or destroy all Confidential Information and any copies thereof.',
    '',
    '---',
    '',
    `**Disclosing Party:** ${disclosingParty}`,
    `**Receiving Party:** ${receivingParty}`,
    '',
    `*This document was generated by Largo M&A Assistant. Review by qualified legal counsel is recommended before execution.*`,
  ];

  return lines.join('\n');
};
